version: '2'

services:
  lava-worker:
    container_name: lava-worker0
    hostname: worker0
    build:
      context: ./
      args:
        version: 2021.05
        server: "lava-server"
        extra_packages: "lava-coordinator"
        pdu_server: 192.168.11.35
    restart: always
